services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: imagepipeline
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-server:
    build: ./api-server
    ports:
      - "8080:8080"
    environment:
      # ── RabbitMQ locales ──
      SPRING_RABBITMQ_HOST: rabbitmq

      # ── MongoDB (Conexión al contenedor local) ──
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/imagepipeline?authSource=admin

      # ── Supabase y JWT (Inyectados desde el .env) ──
      SUPABASE_DB_URL: ${SUPABASE_DB_URL}
      SUPABASE_DB_USER: ${SUPABASE_DB_USER}
      SUPABASE_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}
      JWT_SECRET: ${JWT_SECRET}

    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  image-worker:
    build: ./image-worker
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq

      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}

      SUPABASE_DB_URL: ${SUPABASE_DB_URL}
      SUPABASE_DB_USER: ${SUPABASE_DB_USER}
      SUPABASE_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}

      RABBITMQ_QUEUES_RESIZE: image.resize
      RABBITMQ_QUEUES_COMPRESS: image.compress
      RABBITMQ_QUEUES_WATERMARK: image.watermark
      RABBITMQ_QUEUES_DEAD_LETTER: image.dlq
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 3

volumes:
  mongo-data:
  minio-data: